### ISSUE TITLE
How do I use Tridex Frame Calculator

### ISSUE THREAD

**Issue by rlarudqls630** [FrankenVoron/Tridex#14]
Hi, this is a really cool project I was looking for for such a long time.
However, I cannot find a way to use the docs.
What should I put into "edit these cells"?
Trident build volume or frame dimension or something else?

**Comment by eddietheengineer** [comment]
@rlarudqls630 I've updated some wording on the calculator--hopefully that is helpful to explain. The "edit these cells" would be the standard "Trident" style frame size, and then in the lower right of the calculator it shows how your X build dimension is impacted.

**Comment by rlarudqls630** [comment]
So I need to put the frame dimension right?

**Comment by eddietheengineer** [comment]
so, in the edit cells, you would put the Y and Z build area dimensions that you would like. The stock is 250mm Z and 250mm Y.

Then, you'd adjust the X dimension so that the green boxes on the bottom right match the build area (X) that you need.

![firefox_6udLcwvkdX](https://user-images.githubusercontent.com/11861478/215334201-c5f04871-09dc-44f0-82f9-e8ccf3b5887f.png)

**Comment by rlarudqls630** [comment]
So if I want 300X300 build size 
I need to change X and Y value and match until Dual Material is 300?
or change Y value to 300 and just adjust X values?


nvm i figured it out
thx for the update

**Comment by seacred** [comment]
I wonder how this works - If a Trident Kit with 250x250x250 is needed to build this one why is there 350mm in x and 250mm in y?
Could you explain the calculator in some easy words?
What do i need to change if i want to build one based on a 300x300 Kit?
Will the length of the linear rails also be affected? I guess they should.
Thanks in Advance.
